name: 'setup_python_with_deps'

description: 'Setup Python and dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  poetry-version:
    description: 'Poetry version to use'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash

    - name: Install Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      id: setup_python
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'
        cache-dependency-path: '**/poetry.lock'

    - name: Set Poetry environment
      run: poetry env use ${{ inputs.python-version }}
      shell: bash

    - name: Install dependencies
      run: poetry install --no-interaction
      shell: bash
