name: Checks and Tests

on:
  pull_request:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VER: '3.12'
  POETRY_VER: '2.0.*'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python with dependencies
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ env.PYTHON_VER }}
          poetry-version: ${{ env.POETRY_VER }}

      - name: Download Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks files
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate --output json

      - name: Static checks
        run: make checks
