name: Check and Upload to Databricks

on:
  push:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '1.7.*'

jobs:
  check-upload:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python with dependencies
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}

      - name: Static checks
        run: make checks

#      - name: Unit tests
#        run: make pytest_ci
#
#      - name: Upload test results
#        uses: actions/upload-artifact@v3
#        with:
#          name: pytest-results-${{ github.sha }}
#          path: junit/test-results.xml
#        if: ${{ always() }}

      - name: Upload notebooks to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: make notebooks_upload

      - name: Build and upload Python lib to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: make lib_upload

      - name: Create Databricks jobs
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: make jobs_create
