name: Check and Upload to Databricks

on:
  push:
    branches: [ master ]

env:
  EXECUTION_ENV: 'CI'
  PYTHON_VER: '3.11'
  POETRY_VER: '1.8.*'
  DATABRICKS_CLI_VER: 'v0.221.0'  # https://github.com/databricks/setup-cli/tags

jobs:
  check-upload:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python with dependencies
        uses: ./.github/actions/setup_python
        with:
          python-version: ${{ env.PYTHON_VER }}
          poetry-version: ${{ env.POETRY_VER }}

      - name: Download Databricks CLI
        uses: "databricks/setup-cli@${{ env.DATABRICKS_CLI_VER }}"

      - name: Static checks
        run: make checks

      - name: Validate Databricks files
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate --output json --target prod

      - name: Upload to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle deploy --target prod
